# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ef553d2e8896972dbf6744b16e325038fc8f41559e8b5391de353a224166fd29c9cfad29bf1b627de11775d343890697650ba83bc62ee6b212ff6906b4930da

test:
  secret_key_base: 419985604ff012037fce47409e57f0ed1190c37ba89b8722baee7ef2e20c795062ed30f4d6c1c7007b4c5932c27ee5b0779969d75fff9613941a4d7a7b8ddbfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
